name: code style

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: code-style-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pint:
    runs-on: ubuntu-latest
    name: Pint

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2, pint
          coverage: none

      - name: Run Pint
        run: pint --test
